### ISSUE TITLE
empty csv output for config["functional_selections"]

### ISSUE THREAD

**Issue by fwelsh** [dms-vep/dms-vep-pipeline#97]
I'm trying to run the pipeline for some initial analyses where I don't have replicate samples for antibody selections. After updating the pipeline, I'm getting the following error:

```
WorkflowError:
Error when formatting 'papermill {input.nb} {output.nb} &> {log}' for rule avg_muteffects. 'OutputFiles' object has no attribute 'nb'
```

I'm having a hard time troubleshooting this error, and it may be unrelated to the lack of replicates, but after going through the relevant notebooks + scripts that seems to be the most likely problem? I had a similar issue with rule avg_antibody_escape in the last version of `polyclonal` - see https://github.com/dms-vep/dms-vep-pipeline/issues/54. 

If this is true, it can be fixed by just skipping these averaging steps if there are no replicate libraries or runs for that antibody. @jbloom

**Comment by fwelsh** [comment]
^ I've done some more troubleshooting here, and it doesn't actually look like this is an issue with lack of replicates. Instead, `functional_selections.csv` is getting output as an empty file. I'm struggling to figure out how to fix this. After changing 

```
    output:
        # only make a notebook output for docs if there are functional selections
        **(
            {"nb": "results/notebooks/analyze_func_scores.ipynb"}
            if len(func_selections)
            else {}
        ),
```
into
```
    output:
        # only make a notebook output for docs if there are functional selections
        **(
            {"nb": "results/notebooks/analyze_func_scores.ipynb"}
            if len(func_selections)
            else {"nb":""} # <---- return the keyword arg with an empty string 
        ),
```
which @WillHannon-MCB suggested, I no longer get the error message associated with an empty notebook. The analysis now fails immediately with the error:
```
Building DAG of jobs...
Traceback (most recent call last):
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 1026, in is_same_checksum
    return is_same_checksum_cache[(f, job)]
KeyError: ('results/func_scores/functional_selections.csv', avg_muteffects)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/__init__.py", line 726, in snakemake
    success = workflow.execute(
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/workflow.py", line 800, in execute
    dag.init()
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 205, in init
    self.update_needrun(create_inventory=True)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 1161, in update_needrun
    if update_needrun(job):
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 1095, in update_needrun
    updated_input = [
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 1100, in <listcomp>
    and not is_same_checksum(f, job)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/dag.py", line 1033, in is_same_checksum
    checksums = self.workflow.persistence.input_checksums(job, f)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 344, in input_checksums
    return set(
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 345, in <genexpr>
    self.metadata(output_path).get("input_checksums", {}).get(input_path)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 311, in metadata
    return self._read_record(self._metadata_path, path)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 459, in _read_record_cached
    return self._read_record_uncached(subject, id)
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 462, in _read_record_uncached
    if not self._exists_record(subject, id):
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 468, in _exists_record
    return os.path.exists(self._record_path(subject, id))
  File "/fh/fast/bloom_j/software/miniconda3/envs/dms-vep-pipeline/lib/python3.9/site-packages/snakemake/persistence.py", line 499, in _record_path
    b64id = ["@" + s for s in b64id[:-1]] + [b64id[-1]]
IndexError: list index out of range
```
i.e. `results/func_scores/functional_selections.csv` is empty.

Let me know if anyone has ideas on troubleshooting this!

**Comment by jbloom** [comment]
@fwelsh, can you point me to a specific commit in one of your repos that is giving this error so I can troubleshoot it?

**Comment by fwelsh** [comment]
@jbloom I have a relevant PR open here - https://github.com/dms-vep/flu_h3_hk19_dms/pull/15. Specifically, [this commit](https://github.com/dms-vep/flu_h3_hk19_dms/pull/15/commits/df901c51152ef8ba007a9b8ac6bb2b4285d9da05) is where I've updated the config to be compatible with updated `dms-vep-pipeline`. After this commit, I temporarily reverted `dms-vep-pipeline` so I could just run the analysis.

**Comment by jbloom** [comment]
So if I run off the latest commit on this branch (8969662) I will get the error?

**Comment by fwelsh** [comment]
I haven't tested the latest commit with current pipeline, only the rolled back version, but it should give the same error. Or you can fully replicate running off of commit I linked above ([df901c5](https://github.com/dms-vep/flu_h3_hk19_dms/pull/15/commits/df901c51152ef8ba007a9b8ac6bb2b4285d9da05))
